apiVersion: v1
kind: Service
metadata:
  name: statuzpage-ui-svc
  namespace: statuzpage
spec:
  ports:
  - port: 8282
    protocol: TCP
    targetPort: 8282
  selector:
    app: statuzpage-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}